#!/usr/bin/env python3
"""Check a page generated by collect.py against the repository. Read-only.

    python3 verify.py --root <repo> docs/interactive/index.html

Checks: the HTML parses, the embedded data is valid JSON, the page loads nothing from the
network, the spec-coverage numbers match `cargo xtask spec-coverage`, and the crate list
matches `cargo metadata`. Exits 1 if any check fails.
"""

import argparse
import html.parser
import json
import re
import subprocess
import sys


class Scan(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.external = []
        self.scripts = []
        self._in_script = False

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "script":
            self._in_script = True
            self.scripts.append("")
            if a.get("src"):
                self.external.append(a["src"])
        if tag == "link" and a.get("href"):
            self.external.append(a["href"])
        if tag in ("img", "iframe") and a.get("src", "").startswith(("http:", "https:", "//")):
            self.external.append(a["src"])

    def handle_endtag(self, tag):
        if tag == "script":
            self._in_script = False

    def handle_data(self, data):
        if self._in_script:
            self.scripts[-1] += data


def run(cmd, root):
    return subprocess.run(cmd, cwd=root, capture_output=True, text=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("page")
    args = ap.parse_args()
    failures = []

    text = open(args.page, encoding="utf-8").read()
    scan = Scan()
    scan.feed(text)
    scan.close()
    if scan.external:
        failures.append(f"page loads external resources: {scan.external}")
    m = None
    for script in scan.scripts:
        m = re.search(r"const DATA = (.*?);\n", script, re.S)
        if m:
            break
    if not m or m.group(1).strip() == "/*__TANTU_DATA__*/null":
        print("FAIL: no embedded data (was the template filled?)")
        sys.exit(1)
    try:
        data = json.loads(m.group(1))
    except json.JSONDecodeError as e:
        print(f"FAIL: embedded data is not valid JSON: {e}")
        sys.exit(1)
    c = data["counts"]
    print(f"page: {c['crates']} crates, {c['pub_items']} public items, {c['specs']} specs, "
          f"{c['active_rules']} active rules ({c['covered_rules']} with tests), {c['adrs']} ADRs")

    cov = data["coverage"]
    out = run(["cargo", "xtask", "spec-coverage"], args.root)
    last = (out.stdout.strip().splitlines() or [""])[-1]
    want = (f"spec-coverage: {cov['checked']} checked, {cov['draft']} draft, "
            f"{len(cov['problems'])} problem(s)")
    print(f"xtask: {last}")
    if last != want:
        failures.append(f"spec-coverage mismatch: page says '{want}', xtask says '{last}'")

    meta = run(["cargo", "metadata", "--no-deps", "--format-version", "1"], args.root)
    if meta.returncode == 0:
        names = sorted(p["name"] for p in json.loads(meta.stdout)["packages"])
        page_names = sorted(cr["name"] for cr in data["crates"])
        print(f"cargo metadata: {len(names)} packages")
        if names != page_names:
            failures.append(f"crate list mismatch: cargo {names} vs page {page_names}")
    else:
        failures.append("cargo metadata failed: " + meta.stderr.strip()[:300])

    for f in failures:
        print("FAIL: " + f)
    print("OK" if not failures else f"{len(failures)} check(s) failed")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
