[package]
name = "tantu-platform-winit"
description = "winit implementation of the Tantu `Platform` trait."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tantu-platform = { workspace = true }
